python run_clm.py \
    --config_name checkpoints/gpt2-chinese \
    --tokenizer_name checkpoints/gpt2-chinese \
    --train_file data/train.json \
    --validation_file data/valid.json \
    --cache_dir data \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 2 \
    --num_train_epochs 20 \
    --save_total_limit 2 \
    --do_train \
    --do_eval \
    --save_steps 1000 \
    --logging_steps 100 \
    --output_dir outputs/gpt2-abstract